logger:
  provider: zap # zap | slog
  level: debug
  env: dev
  app_name: podzone_onboarding

redis:
  auth:
    uri: redis://redis:6379/0

mongo:
  onboarding:
    uri: mongodb://podzone:podzone123@mongo:27017/onboarding
    database: catalog
    ping_timeout: 3s
    connect_timeout: 5s

grpc:
  port: 50051
