logger:
  provider: zap # zap | slog
  level: debug
  env: dev
  app_name: podzone_onboarding

consul_kv:
  address: 'http://localhost:8500'
  token: ''
  tls:
    insecure_skip_verify: true

redis:
  auth:
    uri: redis://localhost:6379/0

mongo:
  onboarding:
    uri: mongodb://localhost:27017/onboarding
    database: catalog
    ping_timeout: 3s
    connect_timeout: 5s

pprof:
  enable: false
  addr: '127.0.0.1:6060'
