logger:
  provider: zap # zap | slog
  level: debug
  env: dev
  app_name: podzone_admin_catalog

redis:
  catalog:
    uri: redis://redis:6379/0

mongo:
  catalog:
    uri: mongodb://podzone:podzone123@mongo:27017
    database: catalog
    ping_timeout: 3s
    connect_timeout: 5s

grpc:
  port: 50051
