logger:
  provider: 'zap' # "zap" | "slog" | "noop"
  level: 'info'
  env: 'dev'
  app_name: 'podzone_admin_grpcgateway'

redis:
  auth:
    uri: redis://redis:6379/0
# not use yet
# grpc_client:
#   auth:
#     addr: localhost:50051
#   catalog:
#     addr: localhost:50052
# grpc_gateway:
#   http:
#     port: 8080

pprof:
  enable: false
  addr: '127.0.0.1:6060'
